services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gateway-postgres
    environment:
      POSTGRES_DB: gateway_management
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gateway_user -d gateway_management']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
